# Site settings
title: Sars-CoV-2
description: "A minimal Quizzing blog"
url: "http://www.jacoporabolini.com/emerald"
author:
  name: "Jacopo Rabolini"
  email: "hello@jacoporabolini.com"
  url: "http://www.jacoporabolini.com"

# Build settings
baseurl: /SARS-CoV-2 # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
    classes: wide
# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
